import type { Metadata } from 'next'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navigation/navbar/Navbar'
import TopHeader from './components/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Matthew Jeshua Martin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Image
        src="/artificial-intelligence-4815770.jpg"
        alt="Two Artificial Heads facing each other"
        layout='fill'
        objectFit='cover'
        objectPosition='center'
        style={{zIndex: -5}}
      />
        <TopHeader />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
